# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wplebWzCzHj0B-nB7BVFNwqC7shkvTrO
"""

!pip install ntscraper
from ntscraper import Nitter

nitter_instance_url = "https://nitter.lucabased.xyz"

scraper = Nitter(nitter_instance_url)

tweets = scraper.get_tweets("crisis", mode = 'hashtag', number=10)

final_tweets = []
for x in tweets['tweets']:
    data = [x['link'], x['text'],x['date']]
    final_tweets.append(data)

import pandas as pd
dat = pd.DataFrame(final_tweets, columns =['twitter_link','text','date'])

dat

